"""
Interaction Hash Verification (RFC 9635 §4.2.3)

Verifies the interaction hash returned by the AS callback to ensure
the interaction was not tampered with.
"""

from __future__ import annotations

import hashlib
import hmac


def compute_interaction_hash(
    client_nonce: str,
    server_nonce: str,
    interact_ref: str,
    grant_endpoint: str,
    hash_method: str = "sha-256",
) -> str:
    """
    Compute the interaction hash per RFC 9635 §4.2.3.

    The hash is computed as::

        hash(client_nonce + "\\n" + server_nonce + "\\n"
             + interact_ref + "\\n" + grant_endpoint + "\\n")

    Args:
        client_nonce: The nonce generated by the client instance
        server_nonce: The nonce provided by the AS (interact.finish)
        interact_ref: The interaction reference from the callback
        grant_endpoint: The grant endpoint URL
        hash_method: Hash algorithm ("sha-256" or "sha-512")

    Returns:
        Base64url-encoded hash string

    Raises:
        ValueError: For unsupported hash methods
    """
    import base64

    input_str = f"{client_nonce}\n{server_nonce}\n{interact_ref}\n{grant_endpoint}\n"
    input_bytes = input_str.encode("utf-8")

    if hash_method == "sha-256":
        digest = hashlib.sha256(input_bytes).digest()
    elif hash_method == "sha-512":
        digest = hashlib.sha512(input_bytes).digest()
    else:
        raise ValueError(f"Unsupported hash method: {hash_method}")

    # Base64url encoding (no padding)
    return base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")


def verify_interaction_hash(
    received_hash: str,
    client_nonce: str,
    server_nonce: str,
    interact_ref: str,
    grant_endpoint: str,
    hash_method: str = "sha-256",
) -> bool:
    """
    Verify an interaction hash using timing-safe comparison.

    Args:
        received_hash: The hash received in the callback
        client_nonce: The nonce generated by the client instance
        server_nonce: The nonce provided by the AS
        interact_ref: The interaction reference from the callback
        grant_endpoint: The grant endpoint URL
        hash_method: Hash algorithm ("sha-256" or "sha-512")

    Returns:
        True if the hash is valid, False otherwise
    """
    expected = compute_interaction_hash(
        client_nonce=client_nonce,
        server_nonce=server_nonce,
        interact_ref=interact_ref,
        grant_endpoint=grant_endpoint,
        hash_method=hash_method,
    )

    # Timing-safe comparison to prevent timing attacks
    return hmac.compare_digest(expected, received_hash)
